server:
  port: 80

spring:
  data:
    redis:
      host: redis
      port: 6379
      password:
      timeout: 10

url:
  default: http://payment-processor-default:8080
  fallback: http://payment-processor-fallback:8080
  health: http://payment-processor-default:8080